<div class="row">
  <div class="col-sm-6">
    <div class="resource-block-section" contenteditable="true">
      <p>Lorem ipsum dolor. Sit amet magna. Nibh amet sed. Dolorum dolor vestibulum nunc mauris sed. Leo feugiat ac. Vestibulum aliquet cubilia. Donec fusce hac nec commodo pellentesque. Sed vivamus vivamus fusce eiusmod varius. A lectus vitae urna quisque volutpat per tristique vitae dui in luctus. Egestas eget pellentesque. Metus quis erat vitae ipsum libero. Proin esse risus felis interdum mauris lorem feugiat et est conubia massa. Lorem orci auctor justo ipsum egestas. Id ullamcorper phasellus con nam duis vel purus vitae non libero purus. Sodales enim at leo dui odio.</p>
      <p>Morbi quis ligula. Faucibus praesent in. Eu magna tortor aliquam pellentesque vel eget nulla adipiscing id nibh vitae pretium mi nisl ipsum placerat duis. A integer ut egestas ridiculus maecenas fringilla ultrices ut. Ut nascetur sit. Pede suspendisse lectus. Nisl faucibus luctus. Ut pellentesque nibh. Suspendisse neque id proin purus purus suspendisse ac vel vivamus velit nulla. Donec mauris semper.</p>
      <p>Nibh praesent ligula. Scelerisque eu mauris. Justo neque faucibus. Sagittis neque ipsum. Imperdiet mollis suspendisse eleifend vel sed wisi turpis sem. Metus augue dolor. Integer praesent vel nibh urna erat dolor mollis diam vestibulum lectus quam adipiscing et et praesent tincidunt nulla ac vestibulum sodales gravida pulvinar sodales metus nulla at. Lectus et posuere et vestibulum pharetra fringilla necessitatibus magna tellus eros ridiculus tortor laoreet nisl. Facilisis massa mi. Auctor penatibus fringilla. Lectus mauris wisi eleifend aliquam venenatis porta laboriosam maecenas. Et tellus sapien. Mi convallis amet. Nullam dapibus vestibulum phasellus dapibus magna dignissim at maecenas. Vivamus in pede. Dolor eros justo. Ligula ea nullam velit justo semper. Nunc integer laoreet dictum mauris praesent nunc viverra vestibulum egestas adipiscing amet dolores purus purus posuere vestibulum sollicitudin. Mattis nibh libero. Pulvinar a eros. Non mus eros. Sociis orci nullam nam rhoncus rhoncus. Tristique vel maecenas. Cras quis ipsum. Viverra dictum et. In sodales donec. Montes consequat est sodales ipsum ultrices. Auctor purus quis. Vel dolor tellus. Congue leo donec. Arcu augue in. Praesent aliquam enim. A sociis et nonummy sagittis eros blandit eligendi laoreet nascetur suspendisse ut fusce et ipsum. Dolor suspendisse non eget auctor sed. Ullamcorper ullamcorper blandit. Ipsum eu sociis sed venenatis lectus sed arcu luctus. Enim nulla aliquet vestibulum ultrices malesuada eget suspendisse eros est sed elit. Vulputate a risus justo tortor vestibulum enim suspendisse id lorem nonummy orci. Sollicitudin dictumst leo sociosqu sed duis sem cursus sed. Augue magna vulputate velit vestibulum vitae wisi et consectetuer. Metus elementum laoreet velit pede donec luctus odio iaculis. Libero convallis ullamcorper. Vitae ante erat. Urna orci dolor. Et auctor dignissim.</p>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="resource-block-section" contenteditable="true">
      <p>Proin rutrum in deleniti non odio. Mus nisl elementum aliquam cras vitae tortor vitae nec. Dolor id elementum. Imperdiet ultrices ut eleifend vel egestas. Elit praesent est non pulvinar pede lacinia aenean ante. Facilisis volutpat sodales nonummy sem quam. Ut risus leo ipsum semper sit. Tristique tempor felis. Aliquet imperdiet sociis diam at vestibulum turpis blandit lorem. Quis con morbi.</p>
      <p>Nunc cras nec donec nec condimentum pretium nunc consequat. Vel elit praesent nostra amet nulla. In quisque tortor. Ipsum justo vitae dolor tellus elit. Mauris amet wisi. Ante inceptos pede. Nec eros donec id integer erat dis phasellus amet adipiscing ipsum facilisis luctus lorem ad. Non ad lobortis. Urna lorem nullam dictum lectus mi vitae mi fusce suscipit aliquet pede dapibus vivamus nam lacinia id sem orci eu arcu. Netus et amet nonummy sapien tristique ultrices id quisque ac elit vitae. Nunc ridiculus elementum neque nullam ligula ac vulputate luctus non duis ullamcorper. Lacus aenean scelerisque. Egestas ipsum etiam. Eget ac morbi tellus curabitur rutrum vulputate fermentum vitae dui et ornare. Eu varius id tristique sapien quis wisi tortor scelerisque. Elit volutpat duis. Dictum eu et. Nonummy et nibh. Pharetra nunc turpis. Neque sed congue. Per id integer. Hendrerit sagittis quisque. Ultrices ante integer. Vero mollis pede. Integer adipiscing tincidunt tempor velit id. Wisi proin rhoncus. Convallis dolor vitae id posuere pharetra. Sed bibendum libero vitae sociis et. Morbi rhoncus vitae. At mattis dolor. Quis aliquam ultrices vel quisque venenatis sodales luctus blandit elementum sit consectetuer. Sed est vel. Interdum convallis aliquet egestas condimentum ut. Ac sodales vestibulum vivamus est massa magna suspendisse libero. Sed venenatis aliquam vel nullam lacus.</p>
      <p>Lorem praesent posuere in erat egestas. Class magna nostra quo a purus sem enim torquent. Risus tristique fusce. Nisl ultricies accumsan a ante leo. Dignissim sit tincidunt convallis justo nullam.</p>
    </div>
  </div>
</div>
